# Generated by Django 5.0 on 2023-12-15 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_categories_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='products_base_price',
            field=models.IntegerField(),
        ),
    ]
