# Generated by Django 5.0 on 2023-12-21 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_products_product_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categories',
            new_name='Categorie',
        ),
        migrations.RenameModel(
            old_name='Products',
            new_name='Product',
        ),
    ]
