# Generated by Django 5.0 on 2024-02-02 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auction',
            name='active',
        ),
    ]
