# Generated by Django 5.0 on 2024-02-28 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_t2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='T2',
        ),
    ]
